name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db
        with:
          install: true
      - name: Build Docker image and store in cache
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85
        with:
          context: .
          push: false
          load: true
          tags: exercism/crystal-analyzer
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run Tests in Docker
        run: bin/run-tests-in-docker.sh
  verify-templates:
    name: Check Json files
    runs-on: ubuntu-22.04
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Run check_json.cr
        run: crystal ./bin/check_json.cr
